package com.bridgelabz.jms.enums;

public enum EventType {

    ORDER_CREATED,
    ORDER_PROCESSING,
    INVENTORY_CHECKED,
    PAYMENT_COMPLETED,
    NOTIFICATION_SENT,
    ORDER_COMPLETED,
    ORDER_CANCEL_FAILED,
    ORDER_CANCEL_REQUESTED,
    ORDER_CANCELLED,
    ORDER_RETRIED
}